import {describe,it,expect,vi} from 'vitest';
import {relayAffiliateRequest} from '../../lib/affiliates/shared-relay';
const env={NODE_ENV:'test',SHARED_AFFILIATE_HEALTH_ORIGIN:'https://health.example',SHARED_AFFILIATE_PORTAL_ORIGIN:'https://body.example',SHARED_AFFILIATE_RELAY_SECRET:'synthetic-relay-secret-32-characters-only'};
const reads=['admin/orders','admin/subscriptions','admin/customers','admin/accounting/summary','admin/accounting/trends','admin/accounting/inventory','admin/accounting/purchases','admin/accounting/sales','admin/accounting/expenses','admin/accounting/adjustments','admin/accounting/orders','admin/accounting/items/item-1/history','orders/order-1'];
describe('original shared operational read parity',()=>{
 it.each(reads)('relays exact authorized GET %s without Body filtering',async path=>{const transport=vi.fn(async(_input:string|URL,_init?:RequestInit)=>Response.json({ok:true,names:['Original Name'],ids:['original-id']}));const response=await relayAffiliateRequest(new Request(`https://body.example/api/affiliates/${path}?range=all`,{headers:{cookie:'iqon_affiliate_wp_jwt=synthetic.token.value'}}),{env,fetch:transport});expect(response.status).toBe(200);expect(await response.json()).toEqual({ok:true,names:['Original Name'],ids:['original-id']});expect(String(transport.mock.calls[0][0])).toBe(`https://health.example/api/affiliates/${path}?range=all`);});
 it.each(['POST','PATCH','DELETE','PUT'])('keeps unsafe provider %s unavailable',async method=>{for(const path of reads){const transport=vi.fn();const response=await relayAffiliateRequest(new Request(`https://body.example/api/affiliates/${path}`,{method,headers:{origin:'https://body.example'}}),{env,fetch:transport});expect(response.status).toBe(501);expect(transport).not.toHaveBeenCalled();}});
 it('does not proxy unknown accounting reads or GET detail refresh mutations',async()=>{for(const path of ['admin/accounting/unknown','orders/order-1?refresh=1']){const transport=vi.fn();const response=await relayAffiliateRequest(new Request(`https://body.example/api/affiliates/${path}`),{env,fetch:transport});expect(response.status).toBe(501);expect(transport).not.toHaveBeenCalled();}});
 it('preserves canonical auth rejection rather than an empty ledger',async()=>{const response=await relayAffiliateRequest(new Request('https://body.example/api/affiliates/admin/subscriptions'),{env,fetch:async()=>Response.json({ok:false,error:'Unauthorized'},{status:401})});expect(response.status).toBe(401);expect(await response.json()).toEqual({ok:false,error:'Unauthorized'});});
});
