'use client';
import { useCallback,useEffect,useState } from 'react';
import { RefreshCw,ExternalLink } from 'lucide-react';
type Subscription={id:string;status:string;customerName:string;customerEmail:string;currency:string;total:number;intervalLabel:string;nextBillingAt:string|null;items:{name:string;quantity:number}[];affiliate?:{name:string;code:string}|null};
export default function Subscriptions(){
  const [subscriptions,setSubscriptions]=useState<Subscription[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch('/api/affiliates/admin/subscriptions');const d=await r.json();if(!r.ok)throw new Error(d.error);setSubscriptions(d.subscriptions);}catch(e){setError(e instanceof Error?e.message:'Could not load subscriptions.');}finally{setBusy(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function change(id:string,action:string){if(!window.confirm(`${action[0].toUpperCase()+action.slice(1)} this subscription in Shopify?`))return;setBusy(true);try{const r=await fetch(`/api/affiliates/admin/subscriptions/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:'Could not update subscription.');}finally{setBusy(false);}}
  return <div className="space-y-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-slate-500 mb-2">IQON Supplements</p><h1 className="text-3xl">Subscriptions</h1><p className="text-sm text-slate-500 mt-3 max-w-2xl">Shopify subscriptions and the affiliates who referred them. Product totals below exclude shipping and tax.</p></div><button className="button button-outline" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/> Refresh</button></div>
    <a className="inline-flex items-center gap-2 underline text-sm" href="https://admin.shopify.com/store/nr9zd0-t5/apps" target="_blank" rel="noreferrer">Manage products, billing and delivery frequency in Shopify <ExternalLink size={14}/></a>
    {error&&<p role="alert" className="rounded-lg border border-amber-300 bg-amber-50 p-5 text-sm">{error}</p>}
    {!error&&!busy&&!subscriptions.length&&<p className="p-8 border rounded-lg">No subscriptions are available to this Shopify app yet.</p>}
    {busy&&<p role="status">Loading…</p>}
    <div className="space-y-4">{subscriptions.map(s=><article className="bg-white border rounded-lg p-6" key={s.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg">{s.customerName||s.customerEmail}</h2><p className="text-sm text-slate-500">{s.customerEmail}</p></div><span className="text-sm capitalize">{s.status}</span></div><p className="my-4">{s.items.map(i=>`${i.quantity} × ${i.name}`).join(', ')}</p><p className="text-sm">{new Intl.NumberFormat('en-US',{style:'currency',currency:s.currency}).format(s.total)} · {s.intervalLabel}</p><p className="text-sm text-slate-500 mt-2">Next billing: {s.nextBillingAt?new Date(s.nextBillingAt).toLocaleDateString():'Not scheduled'}{s.affiliate?` · Referred by ${s.affiliate.name} (${s.affiliate.code})`:''}</p><div className="flex gap-4 mt-5">{s.status==='active'&&<button disabled={busy} onClick={()=>void change(s.id,'pause')} className="underline text-sm">Pause</button>}{s.status==='paused'&&<button disabled={busy} onClick={()=>void change(s.id,'resume')} className="underline text-sm">Resume</button>}{['active','paused','failed'].includes(s.status)&&<button disabled={busy} onClick={()=>void change(s.id,'cancel')} className="underline text-sm">Cancel</button>}</div></article>)}</div>
  </div>;
}
