"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronRight, RotateCcw, Search, SlidersHorizontal } from "lucide-react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { money, unitPrice, type Product, type Purchase } from "@/lib/catalog";
import { ProductCard, Quantity, useStore } from "./store-shell";

export function CollectionPage({category}:{category:"all"|"supplements"|"skincare"}){
 const {products,mode}=useStore();
 const [filter,setFilter]=useState("all");const [sort,setSort]=useState("featured");
 const base=products.filter(p=>category==="all"||p.category===category);
 const types=[...new Set(base.map(p=>p.type))];
 const visible=useMemo(()=>{const list=base.filter(p=>filter==="all"||p.type===filter);return [...list].sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:sort==="name"?a.name.localeCompare(b.name):Number(a.number)-Number(b.number));},[base,filter,sort]);
 const title=category==="all"?"The IQON collection.":category==="skincare"?"Care for the skin you’re in.":"The everyday, considered.";
 return <main id="main" key={category}><section className="collection-intro section-pad"><div><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">IQON</Link><ChevronRight size={12}/><span>{category==="all"?"Shop all":category}</span></nav><p className="eyebrow">{category==="all"?"SUPPLEMENTS & SKINCARE":category.toUpperCase()}</p><h1>{title}</h1><p>{category==="skincare"?"A focused ritual. From your first cleanse to your final layer.":category==="supplements"?"A focused collection of daily essentials. Find a format for your routine.":"Daily essentials for the way you live. Explore supplements and skincare through one considered lens."}</p></div><img src={mode==="preview"?(category==="skincare"?"/images/store/campaign-skincare.webp":"/images/store/campaign-supplements.webp"):(base[0]?.campaign||"/images/store/precision.webp")} alt={`The IQON ${category==="all"?"supplements":category} collection`} width={1920} height={1080}/></section>
 <section className="catalog section-pad"><div className="catalog-toolbar"><nav aria-label="Shop collection"><Link className={category==="all"?"active":""} href="/collections/all">Shop all</Link><Link className={category==="supplements"?"active":""} href="/collections/supplements">Supplements</Link><Link className={category==="skincare"?"active":""} href="/collections/skincare">Skincare</Link></nav><div className="sort-controls"><span>{visible.length} products</span><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort products"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="featured">Featured</SelectItem><SelectItem value="low">Price: low to high</SelectItem><SelectItem value="high">Price: high to low</SelectItem><SelectItem value="name">Name: A to Z</SelectItem></SelectContent></Select></div></div><div className="catalog-layout"><aside className="catalog-filters"><p className="eyebrow"><SlidersHorizontal size={14}/> SHOP BY FORMAT</p><RadioGroup value={filter} onValueChange={setFilter} className="format-filter" aria-label="Filter by format">{["all",...types].map(type=><label key={type} className={filter===type?"active":""}><RadioGroupItem value={type}/><span>{type==="all"?"All formats":type}</span><small>{type==="all"?base.length:base.filter(p=>p.type===type).length}</small></label>)}</RadioGroup>{filter!=="all"&&<button className="reset-filter" onClick={()=>setFilter("all")}><RotateCcw size={13}/> Clear filter</button>}<div className="catalog-aside-note"><span>{String(base.length).padStart(2,"0")} ESSENTIALS</span><p>Less noise.<br/>More intention.</p><Link href="/approach">The IQON approach <ArrowUpRight size={15}/></Link></div></aside><div className="product-grid catalog-grid" aria-live="polite">{visible.map(p=><ProductCard key={p.id} product={p}/>)}{!visible.length&&<p className="catalog-empty">{mode==="unavailable"?"The collection is temporarily unavailable. Please try again shortly.":"This collection is coming soon."}</p>}</div></div></section>
 <section className="catalog-crosslink"><img src={mode==="preview"?(category==="skincare"?"/images/store/campaign-supplements.webp":"/images/store/campaign-skincare.webp"):(products.find(p=>p.category!==category)?.campaign||"/images/store/precision.webp")} alt={category==="skincare"?"IQON supplements":"IQON skincare"} loading="lazy"/><div><p className="eyebrow">EXPLORE THE OTHER SIDE</p><h2>{category==="skincare"?"Care from within.":"Care you can feel."}</h2><Link className="button button-dark" href={`/collections/${category==="skincare"?"supplements":"skincare"}`}>Explore {category==="skincare"?"supplements":"skincare"} <ArrowRight size={17}/></Link></div></section></main>;
}

export function ProductPage({product:p}:{product:Product}){
 const {add,products,mode,busy,ready}=useStore();const live=mode==="live";const [variantId,setVariantId]=useState(p.variants?.find(v=>v.available)?.id||p.variants?.[0]?.id||"");const variant=p.variants?.find(v=>v.id===variantId);const available=p.available!==false&&variant?.available!==false;const [quantity,setQuantity]=useState(1);const [purchase,setPurchase]=useState<Purchase>("once");const [frequency,setFrequency]=useState("30");const [activeImage,setActiveImage]=useState(0);const [zoom,setZoom]=useState(false);
 const gallery=p.images||[{src:p.image,alt:`IQON ${p.name} packaging`},{src:p.campaign,alt:`IQON ${p.category} collection`},{src:"/images/store/precision.webp",alt:"IQON silver and serum material study"}];
 const price=variant?.price??unitPrice(p,purchase);const currency=variant?.currency||p.currency;const related=products.filter(other=>other.category===p.category&&other.id!==p.id);
 return <main id="main"><nav className="breadcrumbs product-breadcrumbs section-pad" aria-label="Breadcrumb"><Link href="/">IQON</Link><ChevronRight size={12}/><Link href={`/collections/${p.category}`}>{p.category}</Link><ChevronRight size={12}/><span>{p.name}</span></nav><section className="product-detail section-pad"><div className="product-gallery"><button className="gallery-main" aria-label={`Enlarge ${gallery[activeImage].alt}`} onClick={()=>setZoom(true)}><img src={gallery[activeImage].src} alt={gallery[activeImage].alt} width={1200} height={1200} fetchPriority="high"/><span className="gallery-zoom"><Search size={18}/></span><span className="gallery-count">{String(activeImage+1).padStart(2,"0")} / {String(gallery.length).padStart(2,"0")}</span></button><div className="gallery-thumbs">{gallery.map((image,i)=><button key={image.src} className={activeImage===i?"selected":""} aria-label={`View image ${i+1}: ${image.alt}`} aria-pressed={activeImage===i} onClick={()=>setActiveImage(i)}><img src={image.src} alt=""/></button>)}</div><p className="gallery-note">THE IQON COLLECTION / {p.number}</p></div>
 <div className="purchase-panel"><p className="eyebrow">{p.category.toUpperCase()} / {p.type.toUpperCase()}</p><div className="product-title-row"><h1>{p.name}</h1><span>{money(price,currency)}</span></div><p className="product-size">{variant?.title&&variant.title!=="Default Title"?variant.title:p.size}{p.ritual&&<> <span>·</span> {p.ritual}</>}</p><p className="product-lead">{p.descriptor}</p><p className="product-description">{p.description}</p>{p.variants&&p.variants.length>1?<div className="product-variant-picker"><label htmlFor="product-variant">Select option</label><select id="product-variant" value={variantId} onChange={e=>setVariantId(e.target.value)}>{p.variants.map(v=><option key={v.id} value={v.id}>{v.title}{!v.available?" — Sold out":""}</option>)}</select></div>:p.size&&<div className="product-format"><span>FORMAT</span><strong>{p.size}</strong><Check size={15}/></div>}<RadioGroup className="purchase-options" value={purchase} onValueChange={v=>setPurchase(v as Purchase)} aria-label="Purchase option"><label className={purchase==="once"?"purchase-option selected":"purchase-option"}><RadioGroupItem value="once"/><span><strong>One-time purchase</strong><small>Choose your own rhythm</small></span><b>{money(price,currency)}</b></label>{!live&&<label className={purchase==="subscription"?"purchase-option selected":"purchase-option"}><RadioGroupItem value="subscription"/><span><strong>Subscribe & save</strong><small>15% off recurring deliveries</small></span><b>{money(unitPrice(p,"subscription"),currency)}</b></label>}</RadioGroup>{!live&&purchase==="subscription"&&<div className="delivery-frequency"><span>Deliver every</span><Select value={frequency} onValueChange={setFrequency}><SelectTrigger aria-label="Delivery frequency"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="30">30 days</SelectItem><SelectItem value="60">60 days</SelectItem><SelectItem value="90">90 days</SelectItem></SelectContent></Select><small>Illustrative subscription option</small></div>}<div className="add-to-bag-row"><Quantity value={quantity} setValue={setQuantity} label={p.name}/><button className="button button-dark" disabled={busy||!ready||!available} onClick={()=>add(p.id,quantity,purchase,frequency,variantId)}>{!available?"Currently unavailable":busy?"Updating…":"Add to bag"} <span>{money(price*quantity,currency)}</span></button></div>{!live&&<p className="product-preview-note">Product concept and sample price. This preview does not accept orders.</p>}
 <Accordion type="single" collapsible defaultValue="details" className="product-accordion"><AccordionItem value="details"><AccordionTrigger>Product details</AccordionTrigger><AccordionContent><dl><div><dt>Collection</dt><dd>{p.category}</dd></div><div><dt>Format</dt><dd>{p.size}</dd></div><div><dt>Step / focus</dt><dd>{p.ritual}</dd></div></dl>{!live&&<p>This is a proposed product in the IQON store preview. Final packaging, specifications and availability are to be confirmed.</p>}</AccordionContent></AccordionItem>{!live&&<><AccordionItem value="formula"><AccordionTrigger>{p.category==="skincare"?"Ingredients & formulation":"Supplement facts & ingredients"}</AccordionTrigger><AccordionContent>The approved formula, complete ingredient list and relevant product documentation will be published here before launch.</AccordionContent></AccordionItem><AccordionItem value="use"><AccordionTrigger>How to use</AccordionTrigger><AccordionContent>{p.category==="skincare"?`The proposed place for ${p.name} is the ${p.ritual.toLowerCase()} step. `:""}Directions will be confirmed with the final product. This concept page is not dosing or treatment guidance.</AccordionContent></AccordionItem></>}<AccordionItem value="delivery"><AccordionTrigger>Delivery & returns</AccordionTrigger><AccordionContent>{live?"Available shipping methods, delivery charges, tax, and the store’s return policy are shown at checkout before payment.":"Shipping destinations, delivery estimates and return terms will be confirmed before orders open. No payment or subscription is created in this preview."}</AccordionContent></AccordionItem></Accordion></div></section>
 <section className="pdp-editorial"><img src={p.campaign} alt={`The IQON ${p.category} collection in the studio`} width={1920} height={1080} loading="lazy"/><div><p className="eyebrow">CONSIDERED, TO THE LAST DETAIL</p><h2>{p.category==="skincare"?<>A place for<br/>every step.</>:<>Make room for<br/>the everyday.</>}</h2><p>{p.category==="skincare"?"A focused collection brings the first cleanse, treatment and moisturizing steps into one point of view.":"A considered routine starts with clarity. Explore the collection, compare the formats and find the essentials that fit your everyday."}</p><Link className="under-link" href="/approach">Our approach <ArrowUpRight size={16}/></Link></div></section>
 <section className="related-products section-pad"><div className="section-heading"><div><p className="eyebrow">EXPLORE THE COLLECTION</p><h2>{p.category==="skincare"?"Complete your ritual.":"Alongside your everyday."}</h2></div><Link href={`/collections/${p.category}`} className="under-link">Shop {p.category} <ArrowUpRight size={16}/></Link></div><div className="product-grid related-grid">{related.map(product=><ProductCard key={product.id} product={product}/>)}</div></section><div className="sticky-purchase"><div><img src={p.image} alt=""/><span>{p.name}<small>{p.size}</small></span></div><button className="button button-dark" disabled={busy||!ready||!available} onClick={()=>add(p.id,quantity,purchase,frequency,variantId)}>{!available?"Currently unavailable":busy?"Updating…":"Add to bag"} <span>{money(price*quantity,currency)}</span></button></div><Dialog open={zoom} onOpenChange={setZoom}><DialogContent className="image-dialog"><DialogTitle>{p.name}</DialogTitle><DialogDescription>Image {activeImage+1} of {gallery.length}</DialogDescription><img src={gallery[activeImage].src} alt={gallery[activeImage].alt}/></DialogContent></Dialog></main>;
}
