"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Plus } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { money } from "@/lib/catalog";
import { ProductCard, useStore } from "./store-shell";

export function IQONSite(){
 const {add,products,mode,busy,ready}=useStore();const featured=products.find(p=>p.category==="supplements")||products[0];const skin=products.filter(p=>p.category==="skincare"); const [tab,setTab]=useState("all");
 return <main id="main">
  <section className="home-hero">
   <div className="hero-image-wrap"><img src={mode==="preview"?"/images/store/campaign-supplements.webp":featured?.campaign||"/images/store/precision.webp"} alt="IQON supplement collection in sculpted light on brushed silver" width={1920} height={1080} fetchPriority="high"/></div>
   <div className="hero-copy"><p className="eyebrow">THE EVERYDAY, ELEVATED</p><h1>Daily essentials.<br/><em>Exceptional detail.</em></h1><p className="hero-description">A considered collection of supplements and skincare. For the way you live, every day.</p><div className="hero-actions"><Link href="/collections/supplements" className="button button-light">Shop supplements <ArrowRight size={17}/></Link><Link href="/collections/skincare" className="hero-secondary">Explore skincare <ArrowUpRight size={16}/></Link></div></div>
   {featured&&<div className="hero-product-note"><div><span className="eyebrow">IN THE COLLECTION</span><Link href={`/products/${featured.id}`}>{featured.name} <span>{money(featured.price,featured.currency)}</span></Link></div><button disabled={busy||!ready||featured.available===false} aria-label={`Add ${featured.name} to bag`} onClick={()=>add(featured.id)}><Plus size={23} strokeWidth={1.25}/></button></div>}
  </section>
  <div className="collection-rail"><Link href="/collections/supplements"><span>01</span> Supplements <ArrowRight size={16}/></Link><p>One philosophy. From the inside out.</p><Link href="/collections/skincare"><span>02</span> Skincare <ArrowRight size={16}/></Link></div>
  <section className="featured section-pad" id="collection">
   <Tabs value={tab} onValueChange={setTab}><div className="section-heading"><div><p className="eyebrow">DISCOVER IQON</p><h2>The daily collection.</h2></div><div className="section-heading-actions"><TabsList variant="line" className="collection-tabs"><TabsTrigger value="all">The essentials</TabsTrigger><TabsTrigger value="supplements">Supplements</TabsTrigger><TabsTrigger value="skincare">Skincare</TabsTrigger></TabsList><Link href="/collections/all" className="under-link">Shop all <ArrowUpRight size={16}/></Link></div></div>{["all","supplements","skincare"].map(value=><TabsContent key={value} value={value}><div className="product-grid home-product-grid">{(value==="all"?products.slice(0,4):products.filter(p=>p.category===value)).map(p=><ProductCard key={p.id} product={p}/>)}</div></TabsContent>)}</Tabs>
  </section>
  <section className="skin-story"><div className="skin-story-photo"><img src={mode==="preview"?"/images/store/campaign-skincare.webp":skin[0]?.campaign||"/images/store/precision.webp"} alt="IQON serum and cream with tactile skincare texture and precise silver details" width={1920} height={1080} loading="lazy"/><span className="photo-caption">THE IQON SKINCARE COLLECTION</span></div><div className="skin-story-copy"><p className="eyebrow">A NEW EXPRESSION OF IQON</p><h2>As considered<br/>as the skin<br/><em>you’re in.</em></h2><p>{!skin.length?"A new expression of IQON. Our skincare collection is in development.":"From the first cleanse to the final layer. Explore a focused skincare collection, with a place for every step."}</p><Link href="/collections/skincare" className="button button-dark">Explore skincare <ArrowRight size={18}/></Link><div className="ritual-mini"><span>01 / CLEANSE</span><span>02 / TREAT</span><span>03 / MOISTURIZE</span></div></div></section>
  {!!skin.length&&<section className="routine-shop section-pad"><div className="section-heading"><div><p className="eyebrow">A ROUTINE THAT’S YOUR OWN</p><h2>Your daily ritual. <em>One point of view.</em></h2></div><Link href="/collections/skincare" className="under-link">Build your ritual <ArrowUpRight size={16}/></Link></div><div className="routine-grid">{skin.slice(0,3).map((p,i)=><article key={p.id}><div className="routine-step"><span>0{i+1}</span><p>{p.ritual}</p></div><Link href={`/products/${p.id}`} className="routine-product"><img src={p.image} alt={p.name} loading="lazy"/></Link><div><Link href={`/products/${p.id}`}><h3>{p.name}</h3><p>{p.descriptor}</p></Link><button disabled={busy||!ready||p.available===false} aria-label={`Add ${p.name} to bag`} onClick={()=>add(p.id)}><Plus size={20}/></button></div></article>)}</div></section>}
  <section className="material-story"><div className="material-copy"><p className="eyebrow">THE IQON APPROACH</p><h2>Precision is<br/>in the details.</h2><p>Clarity in the information. Intention in the routine. Attention to the things you see, touch and use every day.</p><Accordion type="single" collapsible defaultValue="clarity" className="brand-principles">{[{id:"clarity",title:"A clear point of view",text:"Useful information belongs beside the product. Our aim is to make every formula, format and place in your routine easy to understand."},{id:"detail",title:"Considered from every angle",text:"From the shape of a jar to the feel of a dispenser, the everyday details deserve attention."},{id:"routine",title:"Your routine, your rhythm",text:"A focused collection makes room for personal choice. Explore the format and steps that fit your everyday."}].map((item,i)=><AccordionItem key={item.id} value={item.id}><AccordionTrigger><span className="principle-label"><small>0{i+1}</small>{item.title}</span></AccordionTrigger><AccordionContent>{item.text}</AccordionContent></AccordionItem>)}</Accordion><Link href="/approach" className="under-link">Discover our approach <ArrowUpRight size={16}/></Link></div><div className="material-image"><img src="/images/store/precision.webp" alt="Macro study of clear serum and precisely machined silver" width={1600} height={1200} loading="lazy"/><span className="photo-caption">MATERIAL STUDY / 01</span></div></section>
  <section className="everyday-story section-pad"><div className="everyday-photo"><img src="/images/store/campaign-lifestyle.webp" alt="Two adults enjoying an unhurried moment in natural daylight" width={1920} height={1080} loading="lazy"/></div><div className="everyday-copy"><p className="eyebrow">MADE FOR THE EVERYDAY</p><h2>A little intention.<br/><em>A life of your own.</em></h2><p>Good routines make room for living. Discover the essentials that earn their place in yours.</p><Link href="/collections/all" className="under-link">Find your essentials <ArrowUpRight size={16}/></Link></div></section>
 </main>;
}
