/** A cohesive photographic system. Metrics are label facts, never clinical outcomes. */
type ProductArt = { scene: string; sceneAlt: string; caption: string; metric: string; metricLabel: string; note: string; macro: string };
const art = (id: string, sceneAlt: string, caption: string, metric: string, metricLabel: string, note: string, format: string): ProductArt => ({ scene: `/images/product-editorial/${id}.webp`, sceneAlt, caption, metric, metricLabel, note, macro: `/images/product-editorial/${format}-macro.webp` });
export const productArt: Record<string, ProductArt> = {
  "creatine-monohydrate": art("creatine-monohydrate", "IQON Creatine Monohydrate with water and a scoop of powder in soft daylight", "Made for your next rep.", "1", "ingredient. Creatine monohydrate.", "Unflavored. No added caffeine or sweeteners.", "powder"),
  "hydrolyzed-collagen-peptides": art("hydrolyzed-collagen-peptides", "IQON Hydrolyzed Collagen Peptides beside a chilled drink", "Your drink. Your collagen ritual.", "1", "ingredient. Bovine collagen peptides.", "Grass-fed. Unflavored. Easy to make your own.", "powder"),
  "collagen-peptides-chocolate": art("collagen-peptides-chocolate", "IQON Chocolate Collagen Peptides with a chocolate drink and cocoa-colored powder", "A daily ritual, with chocolate.", "2", "scoops in your chosen drink.", "Mix with 8–10 oz of liquid in a shaker or blender.", "cocoa"),
  "colostrum-powder": art("colostrum-powder", "IQON Colostrum Powder with a cold drink and a small scoop", "One scoop. A cold drink. Your routine.", "25%", "IgG in the bovine colostrum.", "575 mg IgG within 2,300 mg colostrum per serving.", "powder"),
  "colon-gentle-cleanse": art("colon-gentle-cleanse", "IQON Colon Gentle Cleanse jar, individual sachets and water", "Individually portioned. Ready to mix.", "30", "individual sachets per jar.", "One sachet. 200 mL of still water. Drink promptly.", "sachet"),
  "keto-5": art("keto-5", "IQON Keto-5 with two capsules and a glass of water", "A focused formula for your routine.", "5", "ingredients in the Keto Blend.", "Vegetable capsule format. Contains caffeine.", "capsule"),
  "glp-1-support": art("glp-1-support", "IQON GLP-1 Support on a silver tray with capsules and water", "Keep nutrition in the picture.", "2", "capsules in your daily routine.", "60 capsules per bottle. A 30-day supply.", "capsule"),
  "liver-support": art("liver-support", "IQON Liver Support with capsules and water on a cool grey surface", "A considered botanical blend.", "7", "botanicals. Plus L-cysteine.", "Milk thistle, turmeric and five more botanicals.", "capsule"),
  "nmn": art("nmn", "IQON NMN beside a glass of water and one ivory capsule", "Cellular nutrition. Made simple.", "500 mg", "β-NMN per serving.", "One vegetable capsule daily. 30 capsules per bottle.", "capsule"),
  "resveratrol": art("resveratrol", "IQON Resveratrol with a capsule and water in soft daylight", "Plant science. Clearly defined.", "50%", "trans-resveratrol in the complex.", "600 mg refers to the root complex, not pure trans-resveratrol.", "capsule"),
  "hair-skin-nails-gummies": art("hair-skin-nails-gummies", "IQON Hair, Skin & Nails bottle with ruby gummies on a silver dish", "Your routine, in a different form.", "2", "gummies in your daily routine.", "Passion-fruit flavor. 60 gummies per bottle.", "gummy"),
  "anti-aging-cleanser-with-peptides": art("anti-aging-cleanser-with-peptides", "IQON peptide cleanser with a cotton cloth on a silver shelf", "A clean start. A comfortable finish.", "AM / PM", "your first skincare step.", "Peptides, glycerin and panthenol. Rinse thoroughly.", "water"),
  "hydrating-tonic": art("hydrating-tonic", "IQON Hydrating Tonic with cotton pads and a glass dish", "Hydration without the weight.", "198 mL", "of water-light hydration.", "Aloe, glycerin and sodium PCA. After cleansing.", "water"),
  "exfoliating-pads": art("exfoliating-pads", "IQON Exfoliating Pads with one treatment pad on a silver dish", "A more refined-looking surface.", "3", "acids. One exfoliating step.", "Mandelic, lactic and salicylic acids. 50 pads.", "water"),
  "hydra-c-ferulic-serum": art("hydra-c-ferulic-serum", "IQON Hydra C + Ferulic Serum on brushed silver beside a clear glass dish", "Brightness meets hydration.", "C + F", "vitamin C meets ferulic acid.", "Antioxidant care, with sodium hyaluronate for hydration.", "water"),
  "retinol-rx": art("retinol-rx", "IQON Retinol Rx on brushed aluminum in quiet evening light", "Make room for your evening ritual.", "PM", "your evening treatment step.", "Encapsulated retinol. Introduce gradually. Use daytime SPF.", "water"),
  "firming-peptide-eye-gel": art("firming-peptide-eye-gel", "IQON Firming Peptide Eye Gel with a clear glass dish on a silver ledge", "Fresh eyes. A lighter touch.", "15 mL", "of targeted eye care.", "Peptides, aloe and cucumber water in a light gel.", "water"),
  "copper-peptide-restore-cream": art("copper-peptide-restore-cream", "IQON Copper Peptide Restore Cream with a white cotton cloth", "Finish your routine with comfort.", "GHK-Cu", "copper peptide, with moisture care.", "A multi-peptide cream with shea butter and humectants.", "water"),
};
