/** Editorial explanations from the supplied formulas. These are ingredient roles,
 * not finished-product clinical results. Keep the approved gallery independent. */
export type FormulaSpotlight = {
  label:string; title:string; form:string;
  design:"encapsulated"|"pair"|"layers"|"chain"|"flow"|"single";
  symbols:string[];
  parts:{name:string;role:string}[];
  caption:string;
};
export const formulaSpotlights:Record<string,FormulaSpotlight> = {
  "anti-aging-cleanser-with-peptides":{label:"RINSE-OFF FORMULA",title:"Cleanse with comfort.",form:"Peptides + conditioning care",design:"flow",symbols:["Cleanse","Condition","Rinse"],parts:[{name:"Glycerin",role:"Moisture binding"},{name:"Panthenol",role:"Conditioning"},{name:"Peptides",role:"Formula support"}],caption:"A cleansing step with supporting care. Rinse thoroughly before your leave-on products."},
  "hydrating-tonic":{label:"LIGHTWEIGHT HYDRATION",title:"A layer of moisture.",form:"Humectants + botanicals",design:"layers",symbols:["Glycerin","Sodium PCA","Aloe"],parts:[{name:"Glycerin + PCA",role:"Attract and bind water"},{name:"Aloe + panthenol",role:"Condition the skin"}],caption:"Humectants add hydration in a water-light layer. Follow with your serum and moisturizer."},
  "exfoliating-pads":{label:"THE EXFOLIATING BLEND",title:"Two acid families.",form:"Surface-refining care",design:"pair",symbols:["AHA","BHA"],parts:[{name:"Mandelic + lactic",role:"Alpha hydroxy acids"},{name:"Salicylic acid",role:"Beta hydroxy acid"}],caption:"Three acids in a pre-moistened pad, with glycerin and supporting botanicals."},
  "hydra-c-ferulic-serum":{label:"COMPLEMENTARY INGREDIENTS",title:"Antioxidants, paired.",form:"With a hydration component",design:"pair",symbols:["Vitamin C","Ferulic"],parts:[{name:"Ascorbic acid",role:"The vitamin C form"},{name:"Ferulic acid",role:"Antioxidant partner"},{name:"Hyaluronate",role:"Moisture binding"}],caption:"Vitamin C and ferulic acid share the antioxidant role. Sodium hyaluronate adds hydration."},
  "retinol-rx":{label:"ENCAPSULATED DELIVERY",title:"Retinol, supported.",form:"An evening treatment",design:"encapsulated",symbols:["Retinol"],parts:[{name:"Niacinamide",role:"Complementary care"},{name:"Squalane",role:"Emollient softness"},{name:"Hyaluronate",role:"Water binding"}],caption:"Encapsulation helps protect retinol from light and oxygen. Moisture-focused ingredients complete the formula."},
  "firming-peptide-eye-gel":{label:"THE PEPTIDE COMPONENT",title:"Targeted peptide care.",form:"In a lightweight gel",design:"chain",symbols:["Peptide","Peptide","Peptide"],parts:[{name:"Tripeptide-5",role:"Palmitoyl tripeptide"},{name:"Tripeptide-1",role:"Palmitoyl tripeptide"},{name:"Tetrapeptide-7",role:"Palmitoyl tetrapeptide"}],caption:"Three named peptides, complemented by aloe, cucumber water and moisture-binding ingredients."},
  "copper-peptide-restore-cream":{label:"PEPTIDES + MOISTURE",title:"Hydration has layers.",form:"A rich cream finish",design:"layers",symbols:["Peptide care","Water binding","Softness"],parts:[{name:"Copper peptide",role:"GHK-Cu + peptide blend"},{name:"Humectants",role:"Glycerin + hyaluronate"},{name:"Shea butter",role:"Emollient richness"}],caption:"Peptides, water-binding ingredients and emollients play different roles within the same moisturizer."},
  "creatine-monohydrate":{label:"THE RAPID ENERGY PATHWAY",title:"For repeated effort.",form:"Creatine monohydrate",design:"flow",symbols:["Store","Replenish","Repeat"],parts:[{name:"Phosphocreatine",role:"Stored in muscle"},{name:"ATP",role:"Immediate energy"}],caption:"Creatine supports the system that replenishes ATP during brief, intense exercise.*"},
  "hydrolyzed-collagen-peptides":{label:"SOURCE TO FORM",title:"Collagen, simplified.",form:"One unflavored ingredient",design:"flow",symbols:["Bovine","Hydrolyzed","Peptides"],parts:[{name:"Bovine hide",role:"The collagen source"},{name:"Hydrolyzed",role:"Broken into smaller peptides"}],caption:"A single-ingredient powder leaves the flavor of your drink up to you."},
  "collagen-peptides-chocolate":{label:"THE CHOCOLATE FORMULA",title:"Each part has a role.",form:"Collagen + flavor + sweetness",design:"layers",symbols:["Collagen","Cocoa","Stevia"],parts:[{name:"Collagen peptides",role:"The foundation"},{name:"Cocoa + flavor",role:"Chocolate character"},{name:"Stevia",role:"Sweetness"}],caption:"A flavored alternative to the unflavored powder. Prepare two scoops in a shaker or blender."},
  "colostrum-powder":{label:"UNDERSTAND THE SERVING",title:"One total. Two measures.",form:"Bovine colostrum + its IgG",design:"encapsulated",symbols:["IgG"],parts:[{name:"2,300 mg",role:"Total bovine colostrum"},{name:"575 mg",role:"IgG within that total"}],caption:"IgG is included in the colostrum amount. It is not an extra amount added to the serving."},
  "colon-gentle-cleanse":{label:"THE FIBER FOUNDATION",title:"Designed around psyllium.",form:"Fiber + enzymes + botanicals",design:"layers",symbols:["Psyllium","Enzymes","Botanicals"],parts:[{name:"Psyllium husk",role:"Water-absorbing fiber"},{name:"Four enzymes",role:"Named enzyme blend"},{name:"Ginger + tamarind",role:"Botanical ingredients"}],caption:"Psyllium takes up water. Mix with the full amount of water and drink promptly."},
  "keto-5":{label:"THE FIVE-PART BLEND",title:"Know the ingredients.",form:"Vegetable capsule format",design:"chain",symbols:["Tea","Coffee","Caffeine"],parts:[{name:"Tea + coffee",role:"Plant ingredients"},{name:"Caffeine",role:"Anhydrous form"},{name:"Ketone + garcinia",role:"Complete the blend"}],caption:"Contains caffeine. The total caffeine amount is not supplied, so consider other daily sources."},
  "glp-1-support":{label:"THREE FORMULA COMPONENTS",title:"A broader nutrition formula.",form:"Nutrients + digestive ingredients",design:"layers",symbols:["Nutrients","Digestive blend","Probiotic"],parts:[{name:"Vitamins + minerals",role:"Daily nutrition"},{name:"Digestive blend",role:"Botanicals + enzymes"},{name:"LactoSpore®",role:"Bacillus coagulans"}],caption:"Review the complete listed amounts alongside your existing supplements, including iron and other minerals."},
  "liver-support":{label:"THREE INGREDIENT FORMS",title:"More than a plant list.",form:"Botanicals + an amino acid",design:"layers",symbols:["Powders","Extract","Amino acid"],parts:[{name:"Six plant powders",role:"The botanical base"},{name:"Artichoke extract",role:"Standardized to 5% cynarin"},{name:"L-cysteine HCl",role:"Amino acid ingredient"}],caption:"Powder, standardized extract and amino acid describe different ingredient forms in the same blend."},
  "nmn":{label:"INGREDIENT BIOLOGY",title:"A precursor to NAD+.",form:"β-Nicotinamide mononucleotide",design:"flow",symbols:["NMN","NAD+","Metabolism"],parts:[{name:"NMN",role:"The precursor"},{name:"NAD+",role:"A cellular coenzyme"}],caption:"NAD+ is involved in cellular energy metabolism. Ingredient biology is not a claim that this product slows aging.*"},
  "resveratrol":{label:"READ THE TWO NUMBERS",title:"Amount and composition.",form:"A standardized root complex",design:"pair",symbols:["600 mg","50%"],parts:[{name:"600 mg",role:"Listed root complex"},{name:"50%",role:"Trans-resveratrol proportion"}],caption:"The milligram amount describes the complex. The percentage describes the trans-resveratrol within it."},
  "hair-skin-nails-gummies":{label:"BEYOND A SINGLE NUTRIENT",title:"More than biotin.",form:"A chewable nutrient combination",design:"layers",symbols:["B vitamins","Vitamins + minerals","Collagen"],parts:[{name:"Biotin + B vitamins",role:"Nutrient support"},{name:"A, C, D, E + minerals",role:"Broader combination"},{name:"Fish-derived collagen",role:"Animal-derived ingredient"}],caption:"A pectin gummy with fish-derived collagen and sugars. Check the complete formula for dietary suitability."}
};

export const skincareNotes:Record<string,{title:string;body:string}[]> = {
  "anti-aging-cleanser-with-peptides":[{title:"Rinse-off care",body:"The cleanser removes daily buildup and is rinsed away. Your serum and moisturizer provide the leave-on steps that follow."},{title:"Fragrance",body:"Fragrance appears in the ingredient list. Check the complete list if you avoid fragranced skincare."}],
  "hydrating-tonic":[{title:"Hydration, not exfoliation",body:"Choose this step for lightweight moisture. The separate Exfoliating Pads provide the collection’s acid-based exfoliation step."},{title:"Formula details",body:"The formula includes fragrance and colorants, alongside aloe and humectants."}],
  "exfoliating-pads":[{title:"An active step",body:"Use after cleansing and before moisturizer, following the label for frequency. Plan other exfoliants and retinoids carefully."},{title:"Sun care matters",body:"The AHA formula can increase sun sensitivity. Use sunscreen, wear protective clothing and limit exposure during use and for a week afterwards."}],
  "hydra-c-ferulic-serum":[{title:"The vitamin C form",body:"Ascorbic acid is the vitamin C ingredient. Ferulic acid is its antioxidant partner; sodium hyaluronate has a separate hydration role."},{title:"Fragrance + daytime care",body:"Fragrance is included. When used in the morning, follow with moisturizer and sunscreen."}],
  "retinol-rx":[{title:"Build with tolerance",body:"Introduce gradually and follow the product label. A more frequent application is not a reason to continue through irritation."},{title:"Consider the whole routine",body:"Use SPF 30 or higher by day. Avoid during pregnancy or breastfeeding. Account for retinol in other products, including Copper Peptide Restore Cream."}],
  "firming-peptide-eye-gel":[{title:"Gel rather than cream",body:"A light, cooling option for those who prefer a less rich feel around the eyes. Use a small amount and apply gently."},{title:"Targeted placement",body:"Apply around the eye area after cleansing. Keep the product outside the eyes and avoid direct eye contact."}],
  "copper-peptide-restore-cream":[{title:"Humectants + emollients",body:"Glycerin and sodium hyaluronate bind water. Shea butter adds softness and a richer finish."},{title:"Look beyond the name",body:"The formula also includes retinol and niacinamide. Consider your other active products before layering."}]
};
