'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
export function AffiliateOnboarding(){
  const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [code,setCode]=useState<string|null>(null);
  useEffect(()=>{fetch('/api/affiliates/onboarding').then(r=>r.json()).then(d=>{if(d.ok)setOpen(Boolean(d.needsOnboarding));}).catch(()=>{});},[]);
  async function complete(){setBusy(true);setError('');try{const r=await fetch('/api/affiliates/onboarding',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.welcomeCode)setCode(d.welcomeCode);else setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
  if(!open)return null;
  return <div className="fixed inset-0 z-50 bg-slate-950/30 flex items-center justify-center p-5"><section role="dialog" aria-modal="true" aria-labelledby="welcome-heading" className="bg-white rounded-lg max-w-lg w-full p-8 shadow-xl"><p className="text-xs tracking-widest uppercase text-slate-500 mb-5">IQON Supplements</p><h2 id="welcome-heading" className="text-3xl mb-5">Welcome to your next chapter.</h2><p className="text-slate-600 mb-6">Your creator code, earnings and community are all here. Start with the collection guide, add your payment details, and share your code with a clear affiliate disclosure.</p>{code?<><p>Your personal welcome code:</p><p className="border p-4 my-4 text-xl font-medium">{code}</p><p className="text-sm text-slate-500 mb-5">One use, for the email linked to your affiliate account. The discount appears at Shopify checkout.</p><button className="button button-dark" onClick={()=>setOpen(false)}>Go to my dashboard</button></>:<><div className="flex gap-6 text-sm underline mb-7"><Link href="/affiliates/dashboard/learn" onClick={()=>{void complete();}}>Explore the collection</Link><Link href="/affiliates/dashboard/payment" onClick={()=>{void complete();}}>Payment details</Link></div>{error&&<p role="alert" className="text-red-700 mb-4">{error}</p>}<button className="button button-dark" disabled={busy} onClick={()=>void complete()}>{busy?'Setting up…':'Let’s get started'}</button></>}</section></div>;
}
