'use client';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { affiliatePath,useRecruitmentRef } from '@/lib/affiliates/recruitment-links';
export default function AffiliatesPage(){const ref=useRecruitmentRef();return <main id="main">
  <section className="affiliate-hero"><div className="affiliate-hero-copy"><p className="eyebrow">THE IQON PARTNER PROGRAM</p><h1>Good routines.<br/><em>Shared together.</em></h1><p>Introduce your community to IQON Supplements and skincare. Share what fits your routine, give your audience a personal discount, and earn with every qualifying referral.</p><div className="affiliate-actions"><Link className="button button-dark" href={affiliatePath('/affiliates/signup',ref)}>Become an affiliate <ArrowRight size={17}/></Link><Link className="button button-outline" href={affiliatePath('/affiliates/login',ref)}>Sign in</Link></div></div><img src="/images/supplements/22_group_powders_row.webp" alt="IQON daily supplements collection"/></section>
  <section className="affiliate-benefits" aria-label="Program benefits"><article><span className="eyebrow">01 / SHARE</span><h2>A code of your own.</h2><p>Give your community 15% off with your personal creator code. Your dashboard keeps your links and program details in one place.</p></article><article><span className="eyebrow">02 / EARN</span><h2>20% commission.</h2><p>Earn on qualifying product revenue after discounts, excluding shipping and tax. Returning customers remain connected to your account. Refunds adjust earnings.</p></article><article><span className="eyebrow">03 / GROW</span><h2>Room to build.</h2><p>Track referrals, orders and payouts. Learn about the collection, invite other creators, and stay connected to our team.</p></article></section>
  <section className="px-6 py-16 md:py-24 text-center border-t border-slate-200"><p className="eyebrow mb-4">START YOUR NEXT CHAPTER</p><h2 className="text-3xl md:text-5xl mb-5">A considered approach. A shared opportunity.</h2><p className="text-slate-500 max-w-xl mx-auto mb-8">Apply with your creator details and preferred code. We review each application before activating access. Approved rates and any bonus offers appear in your dashboard.</p><Link className="button button-dark" href={affiliatePath('/affiliates/signup',ref)}>Apply to join <ArrowRight size={17}/></Link></section>
<p className="text-center text-sm pb-12"><Link href="/affiliates/contact" className="underline">Questions? Contact the affiliate team</Link></p></main>;}
