// Audited existing Health read surfaces only. No commerce mutation dispatch.
// Products GET is excluded: its legacy handler reconciles inventory records.
export const ORIGINAL_READ_ROUTES: readonly RegExp[] = [
  /^\/api\/affiliates\/admin\/(?:orders|subscriptions|customers)$/,
  /^\/api\/affiliates\/admin\/accounting\/(?:summary|trends|inventory|purchases|sales|expenses|adjustments|orders)$/,
  /^\/api\/affiliates\/admin\/accounting\/items\/[A-Za-z0-9_-]+\/history$/,
  /^\/api\/affiliates\/orders\/[A-Za-z0-9_-]+$/,
];

// Explicit authority API contract. New routes must be reviewed; never prefix-proxy.
export const SHARED_ROUTES: readonly [RegExp, readonly string[]][] = [
  [new RegExp("^/api/affiliates/admin/affiliate\\-messages/[A-Za-z0-9_-]+$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/admin/affiliate\\-messages/broadcast$"), ["POST"]],
  [new RegExp("^/api/affiliates/admin/affiliate\\-messages$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/affiliates/[A-Za-z0-9_-]+/clients$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/affiliates/[A-Za-z0-9_-]+$"), ["GET", "PATCH", "DELETE"]],
  [new RegExp("^/api/affiliates/admin/affiliates$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/app$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/admin/badges$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/commissions/[A-Za-z0-9_-]+$"), ["DELETE"]],
  [new RegExp("^/api/affiliates/admin/create$"), ["POST"]],
  [new RegExp("^/api/affiliates/admin/dashboard$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/export$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/messages/[A-Za-z0-9_-]+/reply$"), ["POST"]],
  [new RegExp("^/api/affiliates/admin/messages/[A-Za-z0-9_-]+$"), ["PATCH", "DELETE"]],
  [new RegExp("^/api/affiliates/admin/messages$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/notes/[A-Za-z0-9_-]+$"), ["PATCH", "DELETE"]],
  [new RegExp("^/api/affiliates/admin/notes$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/admin/payouts/[A-Za-z0-9_-]+$"), ["DELETE"]],
  [new RegExp("^/api/affiliates/admin/payouts$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/admin/rankings$"), ["GET", "PATCH"]],
  [new RegExp("^/api/affiliates/admin/referrer\\-options$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/requests/[A-Za-z0-9_-]+$"), ["POST", "DELETE"]],
  [new RegExp("^/api/affiliates/admin/requests$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/tiktok/[A-Za-z0-9_-]+$"), ["DELETE"]],
  [new RegExp("^/api/affiliates/admin/tiktok$"), ["GET", "PATCH"]],
  [new RegExp("^/api/affiliates/bank$"), ["GET", "PUT"]],
  [new RegExp("^/api/affiliates/change\\-password$"), ["POST"]],
  [new RegExp("^/api/affiliates/clients$"), ["GET"]],
  [new RegExp("^/api/affiliates/creator\\-code$"), ["POST"]],
  [new RegExp("^/api/affiliates/dashboard$"), ["GET"]],
  [new RegExp("^/api/affiliates/forgot\\-password$"), ["POST"]],
  [new RegExp("^/api/affiliates/invite/lookup$"), ["GET"]],
  [new RegExp("^/api/affiliates/invite$"), ["POST", "GET"]],
  [new RegExp("^/api/affiliates/login$"), ["POST"]],
  [new RegExp("^/api/affiliates/logout$"), ["POST"]],
  [new RegExp("^/api/affiliates/me$"), ["GET"]],
  [new RegExp("^/api/affiliates/messages$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/messages/unread$"), ["GET"]],
  [new RegExp("^/api/affiliates/network$"), ["GET"]],
  [new RegExp("^/api/affiliates/onboarding$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/rankings$"), ["GET"]],
  [new RegExp("^/api/affiliates/referrer\\-search$"), ["GET"]],
  [new RegExp("^/api/affiliates/reset\\-password$"), ["POST"]],
  [new RegExp("^/api/affiliates/roster$"), ["GET"]],
  [new RegExp("^/api/affiliates/signup$"), ["POST"]],
  [new RegExp("^/api/affiliates/tiktok$"), ["GET", "POST"]],
  [new RegExp("^/api/affiliates/shared-session$"), ["GET"]],
  [new RegExp("^/api/affiliates/program$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/program$"), ["GET"]],
  [new RegExp("^/api/affiliates/admin/rates$"), ["GET", "PUT"]],
  [new RegExp("^/api/affiliates/admin/code-sync$"), ["POST"]],
];
